### ISSUE TITLE
Profile.php file needed

### ISSUE THREAD

**Issue by Pythoenixx** [CyberPvt/ProjectPhp#26]
apparently our app need to have the ability to do profile update according to module 1 ( Agent and Product Management).
So my suggestion is  when we login, the login page redirect to Profile.php page, not supplier page or agent page. In the profile page
the user can change:

- username
-  email
- password
- phone no
(all this preferably has sticky note and default value(value from user table), so the user can change easily)
 
This one are not requirement but if not keberatan(and if u r smart) u can oso add the ability to change : 

- role(hard)
- first_name (might need to revamp db)
- last_name (might need to revamp db)

**Comment by Pythoenixx** [comment]
@CyberPvt

**Comment by CyberPvt** [comment]
does it have to redirect to the same page? can't we just add a update profile button after login as role?

**Comment by Pythoenixx** [comment]
I said that it has to redirect to the same page? if so, mb but if u has not noticed yet, the current supplier page and the agent page are no longer useful since I have added most of the functionality of both page in the sidebar( its hard to make sure understand this without showing it). Since both page sooner or later might be deprecated, we can no longer redirect to that pages.  So thats why exactly after we login, it must redirect the user to profile page instead of other page

**Comment by CyberPvt** [comment]
Make sense, so when we login, straight up to update profiles page, and at the sidebar already has a navigation?

**Comment by Pythoenixx** [comment]
Not sure wdym by navigation but ig yes

**Comment by CyberPvt** [comment]
Right when I look at this u comment, noice

**Comment by CyberPvt** [comment]
this should be good for now, lemme know
