### ISSUE TITLE
profile.php

### ISSUE THREAD

**Issue by CyberPvt** [CyberPvt/ProjectPhp#32]
there's profile.php page that i jsut make, it does set changes to users table but not to agents and suppliers, help me fix the code need to go somewhere

**Comment by CyberPvt** [comment]
@Pythoenixx

**Comment by Pythoenixx** [comment]
if i finish with my sales, yea sure

**Comment by CyberPvt** [comment]
Or what if I make a different profile agent and profile supplier

**Comment by Pythoenixx** [comment]
why whats the problem?

**Comment by CyberPvt** [comment]
this issue should be done
