### ISSUE TITLE
Bruhhhhhh

### ISSUE THREAD

**Issue by CyberPvt** [CyberPvt/ProjectPhp#40]
![image](https://github.com/CyberPvt/ProjectPhp/assets/129357662/28f273b0-f89d-47d1-be31-9e8df8d25718)

**Comment by Pythoenixx** [comment]
![image](https://github.com/CyberPvt/ProjectPhp/assets/134304851/756bb54a-5b31-42fd-8c9c-ddedb2c54d06)
is the styling for the button accidental or intentional?

**Comment by CyberPvt** [comment]
intentional 😏
