### ISSUE TITLE
Hear me out

### ISSUE THREAD

**Issue by CyberPvt** [CyberPvt/ProjectPhp#46]
![image](https://github.com/CyberPvt/ProjectPhp/assets/129357662/cf7b159e-a83c-4c16-bad1-f5a1f2024c80)

the number is good, but should it stay tho cause it's kinda long to wait

**Comment by Pythoenixx** [comment]
I literally it make it 6.9 just so people notice it and change it

**Comment by CyberPvt** [comment]
noice
