### ISSUE TITLE
Order module issues

### ISSUE THREAD

**Issue by Pythoenixx** [CyberPvt/ProjectPhp#7]
- agent id should be automatically known by the program to avoid security problem

- the agents preferably use dropdown list of the name of the product instead of asking for the product id

- buat limit min 1 max 10 utk product

- buat option for product order: approve/decline

- buat agent blh pilih byk product dlm satu transaction

**Comment by CyberPvt** [comment]
Before you do anything ,please make a backup T_T 👀

**Comment by FIYREX** [comment]
dah siap boleh close issue
